---
version: 1
previewsEnabled: true

services:
  # A Docker web service
  - type: web
    name: webdis
    env: docker
    repo: https://github.com/render-examples/webdis.git # optional
    envVars:
      - key: REDIS_HOST
        fromRedis:
          name: lightning
          property: host 
      - key: REDIS_PORT
        fromRedis:
          name: lightning
          property: port 
      - key: REDIS_CONNECTION_STRING
        fromRedis:
          name: lightning
          property: connectionString 

redises:
- name: lightning
  plan: pro
  region: oregon


