---
version: 1

services:
- name: lightning
  type: redis
  plan: pro
  region: oregon
  maxmemoryPolicy: noeviction
  ipAllowList:
  - source: 35.197.5.153
    description: home
  - source: 35.230.55.231/32
    description: office
  - source: 216.24.57.0/30
    description: vpn
  - source: 216.38.137.183
- name: thunder
  type: redis
  maxmemoryPolicy: volatile-ttl
  ipAllowList:
  - source: 0.0.0.0/0
    description: errone
- name: imagine
  type: redis
  ipAllowList: []
  maxmemoryPolicy: noeviction



