---
version: 1

services:
- name: lightning
  type: redis
  plan: pro
  region: oregon
  maxmemoryPolicy: noeviction
  ipAllowList:
  - source: 35.197.5.153
    description: home
  - source: 35.230.55.231/32
    description: office
  - source: 216.24.57.0/30
    description: vpn
  - source: 216.38.137.183
- name: thunder
  type: redis
  maxmemoryPolicy: volatile-ttl
  ipAllowList:
  - source: 0.0.0.0/0
    description: errone
- name: imagine
  type: redis
  ipAllowList: []
  maxmemoryPolicy: noeviction
    #
# A Docker web service
- type: web
  name: webdis
  env: docker
  repo: https://github.com/render-examples/webdis.git # optional
  region: oregon # optional (defaults to oregon)
  plan: standard # optional (defaults to starter)
  branch: master # optional (uses repo default)
  dockerCommand: ./webdis.sh # optional (defaults to Dockerfile command)
  numInstances: 1 # optional (defaults to 1)
  healthCheckPath: /
  envVars:
    - key: THUNDER_HOST
      fromService:
        name: thunder
        type: redis
        property: host # available properties are listed below
    - key: THUNDER_PORT
      fromService:
        name: thunder
        type: redis
        property: port
    - key: THUNDER_CONNECTION_STRING
      fromService:
        name: thunder
        type: redis
        property: connectionString
    - key: IMAGINE_HOST
      fromService:
        name: imagine
        type: redis
        property: port
    # - key: IMAGINE_DNE
    #   fromService:
    #     name: imagine
    #     type: redis
    #     property: dne
    - key: REDIS_HOST
      fromService:
        name: lightning
        type: redis
        property: host # available properties are listed below
    - key: REDIS_PORT
      fromService:
        name: lightning
        type: redis
        property: port
    # - key: DNE_PORT
    #   fromService:
    #     name: notARedis
    #     type: redis
    #     property: port
    # - key: DNE_TYPE
    #   fromService:
    #     name: notARedis
    #     type: sdfds
    #     property: port
