---
version: 1

redises:
- name: lightning
  plan: pro
  region: oregon
  maxmemoryPolicy: noeviction
  ipAllowList:
  - source: 35.197.5.153
    description: home
  - source: 35.230.55.230/32
    description: office
  - source: 216.24.57.0/30
    description: vpn
  - source: 216.38.137.182
- name: thunder
  ipAllowList:
  - source: 0.0.0.0/0
- name: imagine
  ipAllowList: []



