---
version: 1
previewsEnabled: true

services:
  # A Docker web service
  - type: web
    name: webdis
    env: docker
    repo: https://github.com/render-examples/webdis.git # optional
    envVars:
      - key: REDIS_HOST
        fromRedis:
          name: lightning
          property: host 
  - type: pserv
    name: sidekiq
    env: ruby
    repo: https://github.com/render-examples/sidekiq.git
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -r ./main.rb
    envVars:
      - key: REDIS_URL
        fromRedis:
          name: lightning
          property: connectionString 
  - type: web
    name: sinatra app
    env: ruby
    repo: https://github.com/render-examples/sidekiq.git
    buildCommand: bundle install
    startCommand: bundle exec ruby main.rb
    envVars:
      - key: REDIS_URL
        fromRedis:
          name: lightning
          property: connectionString 

redises:
- name: lightning
  plan: pro
  region: oregon
- name: thunder


