---
version: 1

services:
- name: lightning
  type: redis
  plan: pro
  region: oregon
  maxmemoryPolicy: noeviction
  ipAllowList:
  - source: 35.197.5.153
    description: home
  - source: 35.230.55.231/32
    description: office
  - source: 216.24.57.0/30
    description: vpn
  - source: 216.38.137.183
- name: thunder
  type: redis
  maxmemoryPolicy: volatile-ttl
  ipAllowList:
  - source: 0.0.0.0/0
    description: errone
- name: imagine
  type: redis
  ipAllowList: []
  maxmemoryPolicy: noeviction
- type: pserv
  # typo: sure
  name: redis
  env: docker
  disk:
    name: data
    mountPath: /var/lib/redis
    sizeGB: 10

databases:
  - name: elephant
    nemo: typo
    databaseName: mydb # optional (Render may add a suffix)
    user: adrian # optional
    ipAllowList: # optional (defaults to allow all)
      - source: 203.0.113.4/30
        description: office
      - source: 198.51.100.1
        description: home



